title: AI Conference Deadlines # (Maintained by @jk.ren)
# email: junkai.ren07@gmail.com
description: Countdowns to ML/Robotics/AI conference & Journal deadlines
author: Junkai Ren

domain: "jkren6.github.io"
baseurl: "/Ai-deadline"

# twitter_username: abhshkdz
# twitter_hashtag: machinelearning
github_username: jkren6
github_repo: Ai-deadline

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']
